//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScannerService.TrayApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScannerService.TrayApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال اجرا بوده.
        /// </summary>
        internal static string AlreadyRunningText {
            get {
                return ResourceManager.GetString("AlreadyRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط نرم افزاری.
        /// </summary>
        internal static string ApiInterfaceText {
            get {
                return ResourceManager.GetString("ApiInterfaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میخواهید اسکنر را ببندید؟
        ///سرویس اسکنر در دسترس نخواهد بود.
        /// </summary>
        internal static string ExitConfirmationText {
            get {
                return ResourceManager.GetString("ExitConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن.
        /// </summary>
        internal static string ExitConfirmationTitle {
            get {
                return ResourceManager.GetString("ExitConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        internal static string ExitMenuItemText {
            get {
                return ResourceManager.GetString("ExitMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open API documentation:\n{0}.
        /// </summary>
        internal static string FailedToOpenApiDocsFormat {
            get {
                return ResourceManager.GetString("FailedToOpenApiDocsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start service:\n{0}.
        /// </summary>
        internal static string FailedToStartServiceFormat {
            get {
                return ResourceManager.GetString("FailedToStartServiceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop service:\n{0}.
        /// </summary>
        internal static string FailedToStopServiceFormat {
            get {
                return ResourceManager.GetString("FailedToStopServiceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health check failed: {0}.
        /// </summary>
        internal static string HealthCheckFailedFormat {
            get {
                return ResourceManager.GetString("HealthCheckFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to show notification: {0}.
        /// </summary>
        internal static string NotificationFailedFormat {
            get {
                return ResourceManager.GetString("NotificationFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا ابتدا سرویس را شروع کنید.
        /// </summary>
        internal static string PleaseStartServiceText {
            get {
                return ResourceManager.GetString("PleaseStartServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکنر.
        /// </summary>
        internal static string ScannerNotificationTitle {
            get {
                return ResourceManager.GetString("ScannerNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکنر فعال.
        /// </summary>
        internal static string ServiceStartedPersian {
            get {
                return ResourceManager.GetString("ServiceStartedPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع شده.
        /// </summary>
        internal static string ServiceStartedText {
            get {
                return ResourceManager.GetString("ServiceStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوقف شده.
        /// </summary>
        internal static string ServiceStoppedNotificationText {
            get {
                return ResourceManager.GetString("ServiceStoppedNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکنر غیرفعال.
        /// </summary>
        internal static string ServiceStoppedPersian {
            get {
                return ResourceManager.GetString("ServiceStoppedPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس اسکنر - متوقف شده.
        /// </summary>
        internal static string ServiceStoppedText {
            get {
                return ResourceManager.GetString("ServiceStoppedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع.
        /// </summary>
        internal static string StartMenuItemText {
            get {
                return ResourceManager.GetString("StartMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status check failed: {0}.
        /// </summary>
        internal static string StatusCheckFailedFormat {
            get {
                return ResourceManager.GetString("StatusCheckFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● اسکنر غیرفعال است.
        /// </summary>
        internal static string StatusInactivePersian {
            get {
                return ResourceManager.GetString("StatusInactivePersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● اسکنر فعال است - localhost:{0}.
        /// </summary>
        internal static string StatusRunningPersianFormat {
            get {
                return ResourceManager.GetString("StatusRunningPersianFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ● اسکنر متوقف شده.
        /// </summary>
        internal static string StatusStoppedPersian {
            get {
                return ResourceManager.GetString("StatusStoppedPersian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقف.
        /// </summary>
        internal static string StopMenuItemText {
            get {
                return ResourceManager.GetString("StopMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI update failed: {0}.
        /// </summary>
        internal static string UiUpdateFailedFormat {
            get {
                return ResourceManager.GetString("UiUpdateFailedFormat", resourceCulture);
            }
        }
    }
}
