<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.23" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageReference Include="NAPS2.Images.Gdi" Version="1.2.1" />
    <PackageReference Include="NAPS2.Images.ImageSharp" Version="1.2.1" />
    <PackageReference Include="NAPS2.Sdk" Version="1.2.1" />
    <PackageReference Include="NAPS2.Sdk.Worker.Win32" Version="1.2.1" />
  </ItemGroup>

</Project>
